/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_whh_testjni_Jna */

#ifndef _Included_com_whh_testjni_Jna
#define _Included_com_whh_testjni_Jna
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_whh_testjni_Jna
 * Method:    getStringFromNDK
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_whh_testjni_Jna_getStringFromNDK
  (JNIEnv *, jobject);

/*
 * Class:     com_whh_testjni_Jna
 * Method:    sum
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_whh_testjni_Jna_sum
  (JNIEnv *, jclass, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
